version: '3'
services:
  app_db:
    image: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"

  app:
    build: ../..
    ports:
      - "8080:8080"
    depends_on:
      - app_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://app_db:5432/app_db
