openapi: 3.0.1
info:
  title: API сервиса платежей
  description: API для управления балансами пользователей и обработки платежей
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки
tags:
  - name: Сервис платежей
    description: API для управления балансами пользователей и платежей
paths:
  /payment/try-pay:
    post:
      tags:
        - Сервис платежей
      summary: Попытка совершить платеж
      description: Списание указанной суммы с баланса пользователя, если доступно достаточно средств
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBalanceRequest'
      responses:
        '200':
          description: Платеж успешно обработан
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Пользователь не найден
        '400':
          description: Неверный запрос
  /payment/{userId}/balance:
    get:
      tags:
        - Сервис платежей
      summary: Получить баланс пользователя
      description: Получение текущего баланса для указанного пользователя
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: string
            format: uuid
            example: 123e4567-e89b-12d3-a456-426614174000
      responses:
        '200':
          description: Баланс успешно получен
          content:
            application/json:
              schema:
                type: number
                format: double
                example: 1000.00
        '404':
          description: Пользователь не найден
  /payment/create-data:
    get:
      tags:
        - Сервис платежей
      summary: Создать тестовые данные
      description: Создание тестового пользователя с начальным балансом для тестирования
      responses:
        '200':
          description: Тестовый пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBalance'
components:
  schemas:
    UserBalance:
      type: object
      description: Информация о балансе пользователя
      properties:
        userId:
          type: string
          format: uuid
          description: Уникальный идентификатор пользователя
          example: 123e4567-e89b-12d3-a456-426614174000
        balance:
          type: number
          format: double
          description: Текущий баланс пользователя
          example: 1000.00
    UserBalanceRequest:
      type: object
      description: Запрос на проведение платежа
      required:
        - userId
        - balance
      properties:
        userId:
          type: string
          format: uuid
          description: ID пользователя, совершающего платеж
          example: 123e4567-e89b-12d3-a456-426614174000
        balance:
          type: number
          format: double
          description: Сумма для списания с баланса пользователя
          example: 100.50
