@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.bea.my_shop.infrastructure.input.controller.CartController#getItemsInCart()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.bea.my_shop.infrastructure.input.controller.CartController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_97406 { 
   	label=bea
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1831051207 { 
   	label=my_shop
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_56254018 { 
   	label=CartController
	labeljust=l
	fillcolor=white
	style=filled
   
   CartController19353452XXXgetItemsInCart0[
	label="+ getItemsInCart()"
	style=filled
	fillcolor=white
	tooltip="CartController

&#10;  список товаров в корзине&#10;  Возвращает:&#10;  используется модель для заполнения шаблона:&#10;  \"items\" - List\<Item\> - список товаров в корзине (id, title, decription, imgPath, count, price)&#10;  \"total\" - суммарная стоимость заказа&#10;  \"empty\" - true, если в корзину не добавлен ни один товар&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_743854143 { 
   	label=ItemAndPriceInfo
	labeljust=l
	fillcolor=white
	style=filled
   
   ItemAndPriceInfo2075951998XXXcartId0[
	label="+ cartId()"
	style=filled
	fillcolor=white
	tooltip="ItemAndPriceInfo

null"
	fontcolor=darkgreen
];

ItemAndPriceInfo2075951998XXXitems0[
	label="+ items()"
	style=filled
	fillcolor=white
	tooltip="ItemAndPriceInfo

null"
	fontcolor=darkgreen
];

ItemAndPriceInfo2075951998XXXtotalPrice0[
	label="+ totalPrice()"
	style=filled
	fillcolor=white
	tooltip="ItemAndPriceInfo

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
CartController19353452XXXgetItemsInCart0 -> ItemAndPriceInfo2075951998XXXcartId0;
CartController19353452XXXgetItemsInCart0 -> ItemAndPriceInfo2075951998XXXitems0;
CartController19353452XXXgetItemsInCart0 -> ItemAndPriceInfo2075951998XXXtotalPrice0;
    
}
@enduml
